apiVersion: apps/v1
kind: Deployment
metadata:
  name: ivolve-lab24-deployment
  labels:
    app: ivolve-lab24
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ivolve-lab24
  template:
    metadata:
      labels:
        app: ivolve-lab24
    spec:
      containers:
      - name: ivolve-lab24
        image: abdelrahmanelhelw/ivolve-lab24_argocd-app:9
        ports:
        - containerPort: 8080
        imagePullPolicy: Always