@Library('ivolve_shared_lib') _

pipeline {
    agent any

    environment {
        IMAGE_NAME="abdelrahmanelhelw/ivolve-lab24_argocd-app"
    }

    tools {
        maven 'maven' 
    }

    stages{


        stage('Run Unit Tests'){
            steps{
                dir('CI-CD/lab24_ArgoCD'){
                    buildJavaApp()
                }
            }
        }

        stage('Build and Push Docker Image and Remove Local Image'){
            steps{
                dir('CI-CD/lab24_ArgoCD'){
                    buildandPushImage("${IMAGE_NAME}:${BUILD_NUMBER}" , "DockerHub")       
                }
            }
        }

    //     stage('Update Deployment File & Deploy to k8s'){
    //     steps{
    //         dir('CI-CD/lab24_ArgoCD'){
    //             deployTokenK8s("${IMAGE_NAME}:${BUILD_NUMBER} ", "deployment.yml" ,"Kubernets" , "https://192.168.49.2:8443")

    //         }

    //     }
    // }        we will deploy the deployment file using ArgoCD instead of Jenkins pipeline 

        stage('Update Deployment File'){
            steps{
                dir('CI-CD/lab24_ArgoCD'){
                    editDeployImage("${IMAGE_NAME}:${BUILD_NUMBER}" , "deployment.yml" )
                }
            }
        }

        stage("Push The New Deployment File into GitHub"){
            steps{
                dir('CI-CD/lab24_ArgoCD'){
                    pushDeploymentOnGit( "deployment.yml" , "git-cred" , "ivolve-tasks" )
                }
            }
        }


}

}